// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Card is one task on the board.
 * 
 * The ID is short and human-typable on purpose: it is how you refer to a task
 * when talking to Anton ("close T3", "give T4 to someone else"), so it has to be
 * something you can read off the screen and say out loud.
 */
export interface Card {
    "id": string;

    /**
     * RunID ties the card to the request that created it.
     */
    "runId": string;

    /**
     * AgentID is who the task is assigned to.
     */
    "agentId": string;

    /**
     * Title is the task itself, in Anton's words.
     */
    "title": string;

    /**
     * Note carries a failure reason for a blocked card.
     */
    "note"?: string;
    "status": Status;
}

/**
 * Status is the column a card sits in.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StatusTodo is assigned but not started.
     */
    StatusTodo = "todo",

    /**
     * StatusDoing is being worked on right now.
     */
    StatusDoing = "doing",

    /**
     * StatusDone finished cleanly.
     */
    StatusDone = "done",

    /**
     * StatusBlocked failed and needs attention.
     */
    StatusBlocked = "blocked",
};
