// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PermissionChoice is one mode as the frontend shows it. The labels live here
 * rather than in the UI so that a mode is described once, next to the flag
 * value it sends.
 */
export interface PermissionChoice {
    "id": PermissionMode;
    "label": string;

    /**
     * Detail says what the mode actually permits, in the terms of what an
     * agent will and will not be able to do.
     */
    "detail": string;

    /**
     * Dangerous marks the mode that removes the last check. The UI asks twice
     * for this one; nothing else about it is different.
     */
    "dangerous"?: boolean;
}

/**
 * PermissionMode is the value passed to the CLI as --permission-mode. The
 * constants are the CLI's own spellings, not Work's: this is the one place the
 * two vocabularies meet, and translating them would only add a table to get
 * wrong.
 */
export enum PermissionMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * PermissionRead lets agents read the project and answer about it. The CLI
     * calls this plan mode: reads and searches go through, edits and shell
     * commands are refused before they run, whatever the agent intended.
     */
    PermissionRead = "plan",

    /**
     * PermissionEdit lets agents do the work: file edits and commands go
     * through without asking. This is the mode Work is built around -- the
     * change review exists precisely because edits land without a prompt --
     * and it is the default.
     */
    PermissionEdit = "acceptEdits",

    /**
     * PermissionAll turns the checks off entirely, including the ones that
     * would have stopped something destructive. The CLI will not honour it
     * until its disclaimer has been accepted once; see BypassAccepted.
     */
    PermissionAll = "bypassPermissions",

    /**
     * DefaultPermission is what Work runs in until the user says otherwise.
     */
    DefaultPermission = "acceptEdits",
};
