// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";

/**
 * Node is one node as it stands after a merge. It is a snapshot: changing it
 * changes nothing in the [State] it came from.
 */
export interface Node {
    "id": string;

    /**
     * Parent is empty for a root.
     */
    "parent"?: string;

    /**
     * Position sorts the node among its siblings.
     */
    "position"?: string;

    /**
     * Fields are the winning value for each field written to this node.
     */
    "fields"?: { [_ in string]?: json$0.RawMessage } | null;

    /**
     * Deleted marks a tombstone. A tombstone keeps its fields, so a viewer can
     * say what was deleted rather than that something was; it is simply not in
     * the tree any more.
     */
    "deleted"?: boolean;
}

/**
 * TreeNode is a node together with the nodes under it, in position order.
 */
export interface TreeNode {
    "id": string;

    /**
     * Parent is empty for a root.
     */
    "parent"?: string;

    /**
     * Position sorts the node among its siblings.
     */
    "position"?: string;

    /**
     * Fields are the winning value for each field written to this node.
     */
    "fields"?: { [_ in string]?: json$0.RawMessage } | null;

    /**
     * Deleted marks a tombstone. A tombstone keeps its fields, so a viewer can
     * say what was deleted rather than that something was; it is simply not in
     * the tree any more.
     */
    "deleted"?: boolean;
    "children"?: TreeNode[] | null;
}
