// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Desk is the agent's fixed spot in the office, in world coordinates.
 * 
 * The canvas renderer uses a fixed logical world (see frontend office/world.ts)
 * so these numbers stay meaningful no matter how the window is resized.
 */
export interface Desk {
    /**
     * X and Y are the centre of the desk surface.
     */
    "x": number;
    "y": number;

    /**
     * SeatX and SeatY are where the agent stands/sits when working.
     */
    "seatX": number;
    "seatY": number;
}

/**
 * Role marks what an agent is for. Anton coordinates; the others specialise.
 */
export enum Role {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleCoordinator = "coordinator",
    RoleSpecialist = "specialist",
};
