// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as workbench$0 from "../../../../../dev.jevido/work/internal/workbench/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "agent:assigned": workbench$0.AgentEvent;
            "agent:error": workbench$0.AgentEvent;
            "agent:finished": workbench$0.AgentEvent;
            "agent:working": workbench$0.AgentEvent;
            "claude:cancelled": workbench$0.ClaudeEvent;
            "claude:error": workbench$0.ClaudeEvent;
            "claude:result": workbench$0.ClaudeEvent;
            "claude:session": workbench$0.ClaudeEvent;
            "claude:text": workbench$0.ClaudeEvent;
            "claude:thinking": workbench$0.ClaudeEvent;
            "claude:tool": workbench$0.ClaudeEvent;
        }
    }
}
