// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Link is one internal link that points at a page which does not exist yet.
 */
export interface Link {
    "space": string;
    "slug": string;
    "label": string;
}
