// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Change is one file a run touched.
 */
export interface Change {
    /**
     * Path is relative to the working tree root.
     */
    "path": string;

    /**
     * Status is "modified", "added" or "deleted".
     */
    "status": string;

    /**
     * Patch is a unified diff, empty for a binary file.
     */
    "patch": string;

    /**
     * Binary marks a file with no readable diff.
     */
    "binary": boolean;

    /**
     * Restorable is false when Work cannot put the file back exactly.
     */
    "restorable": boolean;
}
