// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AvailableEvent is the payload for update:available.
 */
export interface AvailableEvent {
    /**
     * Version is the newer release's tag, as tagged: "v0.2.0".
     */
    "version": string;

    /**
     * ReleaseURL is the release page on GitHub, so the frontend can offer
     * "see what changed" next to "install it".
     */
    "releaseUrl": string;
}
