// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as charted$0 from "../charted/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as claude$0 from "../claude/models.js";

/**
 * DocumentationSite is what documentation mode is pointed at, as the pane needs
 * to draw it.
 */
export interface DocumentationSite {
    /**
     * BaseURL is the site's origin, or empty when this machine has none.
     */
    "baseUrl": string;

    /**
     * Space is the section pages land in.
     */
    "space": string;

    /**
     * Writable is whether a token is set. A site without one can be read in a
     * browser and published to by nobody.
     */
    "writable": boolean;
}

/**
 * Permissions is what agents are allowed to do, the modes that could be
 * chosen instead, and whether the local CLI will honour the dangerous one.
 * 
 * One call rather than three: the toggle needs all of it to draw a single row,
 * and a mode without its label or its warning is not something a person can
 * choose between.
 */
export interface Permissions {
    /**
     * Mode is the mode in force now.
     */
    "mode": claude$0.PermissionMode;

    /**
     * Choices are the modes on offer, least powerful first.
     */
    "choices": claude$0.PermissionChoice[] | null;

    /**
     * BypassAccepted is whether the local Claude CLI has had its
     * skip-permissions disclaimer accepted. When it has not, the CLI silently
     * ignores the dangerous mode, so the UI says so rather than letting a run
     * come back having done nothing.
     */
    "bypassAccepted": boolean;

    /**
     * AcceptCommand is the one command that accepts it, for the UI to show.
     */
    "acceptCommand": string;
}

/**
 * PublishResult is what came back from publishing one page.
 */
export interface PublishResult {
    /**
     * URL is where the page now is, so the pane can offer to open it.
     */
    "url": string;

    /**
     * Broken is the links on this page that point at pages which do not exist
     * yet. Not an error: documentation is written from the outside in.
     */
    "broken": charted$0.Link[] | null;
}
