// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes self-update to the frontend.
 * 
 * It is two things: the owner of the background check's lifetime, and the one
 * call the frontend makes when the user says yes. Everything else about
 * updating -- what the latest release is, whether it is newer, fetching it,
 * verifying it, swapping it in -- is in internal/update, and the frontend
 * learns about it only through the update:available event.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";

/**
 * ApplyUpdate installs the newest release over the running binary and restarts
 * into it.
 * 
 * It returns once the new binary is verified and in place, and the restart
 * follows a fraction of a second later -- so the caller does get a resolved
 * promise, and should use it to show that Work is about to disappear and come
 * back rather than to report success and carry on. An error means nothing was
 * installed and the running Work is untouched.
 * 
 * The download is not bound to the app's shutdown context: it has its own
 * timeout, and the only thing that should abandon a user-initiated install
 * halfway is the process ending, which takes it with it anyway.
 */
export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3270829580);
}

/**
 * CheckForUpdates asks GitHub now instead of waiting for the next poll, and
 * answers with what it saw.
 * 
 * The answer comes back rather than only being emitted, because a person
 * pressed a button: "you are on the newest one" is a result, and an event that
 * fires only on good news leaves the button with nothing to say the rest of
 * the time. The popup still appears on its own when the release is newer.
 */
export function CheckForUpdates(): $CancellablePromise<update$0.Found> {
    return $Call.ByID(1717201598);
}

/**
 * Version is the release this binary was built as, or "dev" for a build that
 * was not stamped by the release workflow.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(2322600245);
}
