// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Desk is the agent's fixed spot in the office, in world coordinates.
 * 
 * The canvas renderer uses a fixed logical world (see frontend office/world.ts)
 * so these numbers stay meaningful no matter how the window is resized. The
 * layout is a classroom: the coordinator's desk is at the front, the
 * specialists' desks face it from below.
 */
export interface Desk {
    /**
     * X and Y are the centre of the desk surface.
     */
    "x": number;
    "y": number;

    /**
     * SeatX and SeatY are where the agent stands/sits when working. A seat is
     * always in front of its desk, so the desk reads as furniture the agent is
     * working at rather than something they are standing on.
     */
    "seatX": number;
    "seatY": number;
}

/**
 * Profile is what an agent's folder currently says about them.
 * 
 * Everything here is read at call time rather than taken from the last scan:
 * the panel that shows it is opened by someone who may have just edited the
 * file, and stale text in the one view whose whole job is to show the file
 * would read as a bug rather than as a cache.
 */
export interface Profile {
    "id": string;

    /**
     * Dir is the folder this was read from, empty for a built-in agent that
     * has no folder behind it.
     */
    "dir"?: string;

    /**
     * Skills are the names in skills/, one per skill folder or file.
     */
    "skills": string[] | null;

    /**
     * Skillset is the built-in skillset, if this agent has one. It is Work's
     * rather than the folder's, which is why it is separate from Skills.
     */
    "skillset": string[] | null;

    /**
     * Blurb is the one line the coordinator routes this agent on, whichever of
     * the two it comes from, so nothing has to work that rule out again.
     */
    "blurb"?: string;

    /**
     * Personality is PERSONALITY.md without its heading.
     */
    "personality"?: string;

    /**
     * Avatar is the picture in the folder, if it holds one.
     */
    "avatar"?: string;
}

/**
 * Role marks what an agent is for. Anton coordinates; the others specialise.
 */
export enum Role {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleCoordinator = "coordinator",
    RoleSpecialist = "specialist",
};
