// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as WorkbenchService from "./workbenchservice.js";
export {
    WorkbenchService
};
