// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as claude$0 from "../internal/claude/models.js";

/**
 * Permissions is what agents are allowed to do, the modes that could be
 * chosen instead, and whether the local CLI will honour the dangerous one.
 * 
 * One call rather than three: the toggle needs all of it to draw a single row,
 * and a mode without its label or its warning is not something a person can
 * choose between.
 */
export interface Permissions {
    /**
     * Mode is the mode in force now.
     */
    "mode": claude$0.PermissionMode;

    /**
     * Choices are the modes on offer, least powerful first.
     */
    "choices": claude$0.PermissionChoice[] | null;

    /**
     * BypassAccepted is whether the local Claude CLI has had its
     * skip-permissions disclaimer accepted. When it has not, the CLI silently
     * ignores the dangerous mode, so the UI says so rather than letting a run
     * come back having done nothing.
     */
    "bypassAccepted": boolean;

    /**
     * AcceptCommand is the one command that accepts it, for the UI to show.
     */
    "acceptCommand": string;
}
