// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes self-update to the frontend.
 * 
 * It is two things: the owner of the background check's lifetime, and the one
 * call the frontend makes when the user says yes. Everything else about
 * updating -- what the latest release is, whether it is newer, fetching it,
 * verifying it, swapping it in -- is in internal/update, and the frontend
 * learns about it only through the update:available event.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ApplyUpdate installs the newest release over the running binary and restarts
 * into it.
 * 
 * It returns once the new binary is verified and in place, and the restart
 * follows a fraction of a second later -- so the caller does get a resolved
 * promise, and should use it to show that Work is about to disappear and come
 * back rather than to report success and carry on. An error means nothing was
 * installed and the running Work is untouched.
 * 
 * The download is not bound to the app's shutdown context: it has its own
 * timeout, and the only thing that should abandon a user-initiated install
 * halfway is the process ending, which takes it with it anyway.
 */
export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1317830799);
}

/**
 * Version is the release this binary was built as, or "dev" for a build that
 * was not stamped by the release workflow.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(1239790594);
}
